version: '3.9'
services:

    proxy:
      build: ./proxy
      command: -de
      volumes:
        - ./proxy:/etc/kamailio

    uac:
      build: ./proxy
      entrypoint: sh
      working_dir: /sipp
      tty: true
      volumes:
        - ./uac:/sipp

    uas:
        build: ./proxy
        entrypoint: sh
        tty: true
        volumes:
            - ./uas:/etc/kamailio
